# Generated by Django 3.0.6 on 2020-06-09 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_articulo',
            name='slug',
            field=models.SlugField(max_length=200, unique=True, verbose_name='texto_bonis'),
        ),
    ]
