# Generated by Django 3.0.6 on 2020-06-09 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200609_0125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_articulo',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True, verbose_name='texto_bonis'),
        ),
    ]
