# Generated by Django 3.0.6 on 2020-06-10 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200609_0141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriatas',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='categoriatas',
            name='titulo',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
