# Generated by Django 3.0.6 on 2020-06-11 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200610_0047'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcercaDMI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, null=True)),
                ('foto_perfil', models.ImageField(upload_to='photos_admin')),
                ('estudios', models.TextField(max_length=255, null=True)),
                ('descripcion_minimus', models.TextField(blank=True, max_length=500, null=True)),
                ('facebook', models.URLField(blank=True, verbose_name='facebook')),
                ('web_page', models.URLField(blank=True, verbose_name='pagina web')),
                ('twitter', models.URLField(blank=True, verbose_name='twitter')),
                ('linkidn', models.URLField(blank=True, verbose_name='linkidn')),
                ('slug', models.SlugField(blank=True, max_length=200)),
            ],
        ),
    ]
